train_model:
  KNeighborsClassifier:
    algorithm:
    - auto
    - ball_tree
    - kd_tree
    - brute
    weights:
    - uniform
    - distance
    n_neighbors:
    - 3
    - 5
    - 9
  RandomForestClassifier:
    max_depth:
    - 10
    - 15
    - 20
    max_features:
    - sqrt
    - log2
    n_estimators:
    - 3
    - 5
    - 9
base_model_score: '0.6'